#!/bin/bash

export KERNEL=linux
export IMAGE=image
export IMG_NAME=stretch

if [ ! -f ".port" ]; then
port=$(date +%N);
((port=$port%60000+5525));
echo "using $port"
echo -n $port > .port
fi;

port_num=$(cat .port);

qemu-system-x86_64 \
  -kernel $KERNEL/arch/x86/boot/bzImage \
  -append "console=ttyS0 root=/dev/sda debug earlyprintk=serial slub_debug=QUZ"\
  -hda $IMAGE/${IMG_NAME}.img \
  -net user,hostfwd=tcp::$port_num-:22 -net nic \
  -enable-kvm \
  -nographic \
  -smp 2 \
  -m 2G -s
