#!/bin/bash

# 0 mean non-stop
repeat_time=0
# proc used in executing programs
proc_num=8
# thread mode
thread_mode=1
# collide mode
collide_mode=1
# sandbox option
sandbox_opt="none"
# default log file
prog="syz"

if [ "$#" -eq 1 ]; then
	prog=$1
fi

echo $prog

./bin/syz-execprog -executor=./bin/syz-executor -sandbox=${sandbox_opt} -threaded=${thread_mode} -collide=${collide_mode} -repeat=${repeat_time} -procs=${proc_num} -cover=0 $prog
